<div class="row">
    <?php $nome = "notificacao / index"?>
    <i class="icon-time"></i>
    <h1><?php print  $nome;?></h1>
    <br/>
</div>
<!--
    ESBOÇO DO LAYOUT DE NOTIFICAÇÃO SUJEITO À ALTERAÇÕES
-->
<div class="container">
    <div class="row">
      <div class="col-md-1"><i class="fa fa-user fa-3x"></i>photo</div>
        <div class="col-md-5">
            <div class="row">
                <div class="col-md-12">Vou me atrasar, chego em <span class="label label-success"> 15 min. </span></div> 
                <!--<div class="col-md-2"></div>-->
            </div><br/>
            <div class="row">
                <div class="col-md-6">prof. Adriano há <span class="label label-default">15 min</span></div>
                <div class="col-md-2"><i class="fa fa-clock-o fa-2x"></i></div>
            </div>
      </div>
    </div><hr>
    <div class="row">
      <div class="col-md-1"><i class="fa fa-user fa-3x"></i>photo</div>
        <div class="col-md-5">
            <div class="row">
                <div class="col-md-12">Prof. Igor fez check-in <span class="label label-success"> Lab. Info. B-III></span></div> 
              <!--<div class="col-md-2"></div>-->
            </div><br/>
            <div class="row">
              <div class="col-md-6">há <span class="label label-default">15 min</span></div>
              <div class="col-md-2"><i class="fa fa-check-square-o fa-2x"></i></div>
            </div>
      </div>
    </div><hr>
    <div class="row">
      <div class="col-md-1"><i class="fa fa-user fa-3x"></i>photo</div>
        <div class="col-md-5">
            <div class="row">
              <div class="col-md-10">Aula de <span class="label label-primary">APSOO</span> em <span class="label label-success"> Lab. Info. B-III</span></div> 
              <!--<div class="col-md-2"></div>-->
            </div><br/>
            <div class="row">
              <div class="col-md-6">prof. Adriano há <span class="label label-default">15 min</span></div>
                <div class="col-md-2"><i class="fa fa-refresh fa-2x"></i></div>
            </div>
      </div>
    </div>
</div>